security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
                 users:
                     admin:
                         password: admin
                         roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            provider: in_memory
            anonymous: ~
            form_login:
                  login_path: /login
                  check_path: /login_check
                  default_target_path: homepage
                  # csrf token options
                  csrf_parameter: _csrf_token
            logout: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
