homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

check_data:
    pattern:  /check_data
    defaults: { _controller: AppBundle:CheckData:check }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: AppBundle:Security:loginCheck }

logout:
   pattern: /logout



